### Create a new dish
POST http://localhost:8000/api/dishes
Content-Type: application/json
Accept: application/json

{
  "name": "Test Dish4",
  "description": "This is the test dish",
  "price": "100",
  "category": "61ffa86eca2ed11d78612000",
  "photo": {
      "data": "123",
      "contentType": "image/jpg"
    }
}

### Get all dishes
GET http://localhost:8000/api/dishes
Accept: application/json

### Get dish by id
GET http://localhost:8000/api/dishes/6201de104605dd60e272dff0
Accept: application/json

### Get photo
GET http://localhost:8000/api/dishes/6201de104605dd60e272dff0/photo
Accept: image/jpeg