### Create User
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFENnBoQmhabzMzM3ZuMEtib1p6bCJ9.eyJpc3MiOiJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJHMTl3cDB0WmY0ZUtKbjlnUG5uWE1xSkZobnpNVDl1a0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGktZGF2aWRjaHVzY2hpbmFiaXN0cm8iLCJpYXQiOjE2NDY3OTI0MDEsImV4cCI6MTY0Njg3ODgwMSwiYXpwIjoiRzE5d3AwdFpmNGVLSm45Z1BublhNcUpGaG56TVQ5dWsiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CbFZ6hNlHckZB6gt-XSZ-ffvas82OAe3ClnCnzBNkVUVNK9ihodZ9e0Q7qQqcQ2HBHq04FLU4pdyW49jAXiFBCH7m3dyRNrwESARkVEClkL78d8lt2_50q3nbA4SLTlgCrRu4PvsUR85diB1C4svdpcxxTsdNhgKPsB2hTPWpTDrmD16ZF8VVCqgfn3J52VDI3nKnra9PWIKt_JdsjtanBvYqSWY4otNOe6Q391o3kgRDBRnu44zvcYbLlIamgv69S9rIM11PZQdJLcelUOQk30B9eze_QEE_s3F3v6saF171pZ6Y9RHQjM3D6opctZPuXY13v3jGoVc01IKDp3hG

{
  "_id": "Test03",
  "email": "test03@gmail.com"
}