### Create User
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFENnBoQmhabzMzM3ZuMEtib1p6bCJ9.eyJpc3MiOiJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJHMTl3cDB0WmY0ZUtKbjlnUG5uWE1xSkZobnpNVDl1a0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGktZGF2aWRjaHVzY2hpbmFiaXN0cm8iLCJpYXQiOjE2NDY3OTI0MDEsImV4cCI6MTY0Njg3ODgwMSwiYXpwIjoiRzE5d3AwdFpmNGVLSm45Z1BublhNcUpGaG56TVQ5dWsiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CbFZ6hNlHckZB6gt-XSZ-ffvas82OAe3ClnCnzBNkVUVNK9ihodZ9e0Q7qQqcQ2HBHq04FLU4pdyW49jAXiFBCH7m3dyRNrwESARkVEClkL78d8lt2_50q3nbA4SLTlgCrRu4PvsUR85diB1C4svdpcxxTsdNhgKPsB2hTPWpTDrmD16ZF8VVCqgfn3J52VDI3nKnra9PWIKt_JdsjtanBvYqSWY4otNOe6Q391o3kgRDBRnu44zvcYbLlIamgv69S9rIM11PZQdJLcelUOQk30B9eze_QEE_s3F3v6saF171pZ6Y9RHQjM3D6opctZPuXY13v3jGoVc01IKDp3hG

{
  "_id": "Test03",
  "email": "test03@gmail.com"
}

### Get User By Id
GET http://localhost:8000/api/users/622815c479736a0070430163
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFENnBoQmhabzMzM3ZuMEtib1p6bCJ9.eyJpc3MiOiJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJHMTl3cDB0WmY0ZUtKbjlnUG5uWE1xSkZobnpNVDl1a0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hcGktZGF2aWRjaHVzY2hpbmFiaXN0cm8iLCJpYXQiOjE2NDY5Nzk4MTgsImV4cCI6MTY0NzA2NjIxOCwiYXpwIjoiRzE5d3AwdFpmNGVLSm45Z1BublhNcUpGaG56TVQ5dWsiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.Wb7qPf8svmRMREvJVlsGa75IoAZ_q7dua3Nwy7XLusKZOr7WSFgwOW9opU-RAdUZHfD-L50oK9YjJewXCfds7aHKHw296vWkh6bp-1__ewLujWQvxPg-IDa5qSg-lCO7uOXKr7oWFEqn-8pYOWUXb09hWFE6eR8xbHB-TnugU_ppvgl8MHOOHRTF-hRf4WSE64Zd-ps8WxaSDy_L53Meez2B1IKlMhp6ml8RA2G7lOHalbi7Fv_uPLFDODnX2SKSNiZ7OS2vM1oJXPVlKEzH4c_9bRweG7QxpDyp2Vfla0Dv_C_16LQhQvBrDp-7CXM0d6RkhZF8hRM9IdgC-M4pHQ

### Update Address
PUT http://localhost:8000/api/users/621f191b17a284006ab6dfb1/address
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFENnBoQmhabzMzM3ZuMEtib1p6bCJ9.eyJpc3MiOiJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MjI4MTVjNDc5NzM2YTAwNzA0MzAxNjMiLCJhdWQiOlsiaHR0cHM6Ly9hcGktZGF2aWRjaHVzY2hpbmFiaXN0cm8iLCJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDc0MTUxOTUsImV4cCI6MTY0NzUwMTU5NSwiYXpwIjoiQWpKOHNtWlNyMlIxajdXYktqczZ2RHBzd0xOU3BDSVgiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.IlEr9_v5kvvB7xLfFfbneY-kHPtr3YwpAbFbnjSVEPYYLI76nXNUEgOPeSbvX2i_nyLUxVScY5WYi_70rRaOMa1zylFNNabxXl9RRTl4-4W1RKq66XYa4eymyjkwo7CCx1wsLaUnWKBnWMDfBKjS-yueRzfgSLwdUmpMx2Y020Z_7zYJTBLi3cOg3ZYmOpH17SWPwR40q2sTJ_UTSWv7E0oep0uIFaN7qhdd7wIh_Xx45238Gl9HIfcEftahtQ_c27zVbxqDh9p834Q3IsnpNHAXD1cDAAlq12-2V3JIYUbsZDkZZZvSkThkiroom4tA9uIvdzL_88a3t6UAVaJWqA

{
  "full_name": "Test",
  "line1": "ABC Lane",
  "line2": "AKA Building",
  "state": "HK",
  "zip": "99903",
  "city": "Hong Kong",
  "country": "China",
  "phone": "67859637"
}

### Get address for user
GET http://localhost:8000/api/users/622815c479736a0070430163/address
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFENnBoQmhabzMzM3ZuMEtib1p6bCJ9.eyJpc3MiOiJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MjI4MTVjNDc5NzM2YTAwNzA0MzAxNjMiLCJhdWQiOlsiaHR0cHM6Ly9hcGktZGF2aWRjaHVzY2hpbmFiaXN0cm8iLCJodHRwczovL2RhdmlkY2h1c2NoaW5hYmlzdHJvLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDc0MTUxOTUsImV4cCI6MTY0NzUwMTU5NSwiYXpwIjoiQWpKOHNtWlNyMlIxajdXYktqczZ2RHBzd0xOU3BDSVgiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.IlEr9_v5kvvB7xLfFfbneY-kHPtr3YwpAbFbnjSVEPYYLI76nXNUEgOPeSbvX2i_nyLUxVScY5WYi_70rRaOMa1zylFNNabxXl9RRTl4-4W1RKq66XYa4eymyjkwo7CCx1wsLaUnWKBnWMDfBKjS-yueRzfgSLwdUmpMx2Y020Z_7zYJTBLi3cOg3ZYmOpH17SWPwR40q2sTJ_UTSWv7E0oep0uIFaN7qhdd7wIh_Xx45238Gl9HIfcEftahtQ_c27zVbxqDh9p834Q3IsnpNHAXD1cDAAlq12-2V3JIYUbsZDkZZZvSkThkiroom4tA9uIvdzL_88a3t6UAVaJWqA